# Generated by Django 5.2.6 on 2026-04-28 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('jobtype', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote')], max_length=20)),
                ('jobtime', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time')], max_length=20)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('required_skills', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_experience', models.FloatField(default=5)),
                ('weight_skills', models.FloatField(default=25)),
                ('weight_projects', models.FloatField(default=50)),
                ('weight_education', models.FloatField(default=10)),
                ('weight_institute', models.FloatField(default=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who posted this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_all_jobs', 'Can view all jobs'), ('manage_all_jobs', 'Can manage all jobs')],
            },
        ),
    ]
