# Generated by Django 5.2.6 on 2026-04-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('prior_experience', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('skill_set', models.TextField(blank=True, help_text='Comma-separated skills')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LinkedInScrapingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile_url', models.URLField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linkedin_scraping_activity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_source', models.CharField(blank=True, help_text='Which resume/application was used for extraction', max_length=100)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills: [{name, category, proficiency}]')),
                ('experience', models.JSONField(blank=True, default=list, help_text='Work experience: [{company, title, duration, description}]')),
                ('education', models.JSONField(blank=True, default=list, help_text='Education: [{institution, degree, field, year}]')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Certifications: [{name, issuer, year}]')),
                ('summary', models.TextField(blank=True, help_text='Professional summary/bio extracted from resume')),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, help_text='Total years of professional experience', max_digits=4, null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL', max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True)),
                ('linkedin_scrape_status', models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Current status of the LinkedIn background scrape', max_length=20)),
                ('social_insights', models.JSONField(blank=True, default=dict, help_text='Scraped data from social profiles (e.g. LinkedIn)')),
                ('raw_extraction', models.JSONField(blank=True, default=dict, help_text='Complete LLM response for debugging')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
                'ordering': ['-extracted_at'],
            },
        ),
    ]
