export const SKILL_OPTIONS = [
    // Languages
    { value: 'JavaScript', label: 'JavaScript' },
    { value: 'TypeScript', label: 'TypeScript' },
    { value: 'Python', label: 'Python' },
    { value: 'Java', label: 'Java' },
    { value: 'C++', label: 'C++' },
    { value: 'C#', label: 'C#' },
    { value: 'Go', label: 'Go' },
    { value: 'Rust', label: 'Rust' },
    { value: 'PHP', label: 'PHP' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'Swift', label: 'Swift' },
    { value: 'Kotlin', label: 'Kotlin' },
    { value: 'Dart', label: 'Dart' },
    { value: 'Scala', label: 'Scala' },
    { value: 'Haskell', label: 'Haskell' },
    { value: 'SQL', label: 'SQL' },
    { value: 'R', label: 'R' },
    { value: 'MATLAB', label: 'MATLAB' },

    // Frontend
    { value: 'React', label: 'React' },
    { value: 'Vue.js', label: 'Vue.js' },
    { value: 'Angular', label: 'Angular' },
    { value: 'Next.js', label: 'Next.js' },
    { value: 'Svelte', label: 'Svelte' },
    { value: 'Nuxt.js', label: 'Nuxt.js' },
    { value: 'Redux', label: 'Redux' },
    { value: 'Tailwind CSS', label: 'Tailwind CSS' },
    { value: 'Bootstrap', label: 'Bootstrap' },
    { value: 'Material UI', label: 'Material UI' },
    { value: 'Sass', label: 'Sass' },
    { value: 'HTML5', label: 'HTML5' },
    { value: 'CSS3', label: 'CSS3' },
    { value: 'Webpack', label: 'Webpack' },
    { value: 'Vite', label: 'Vite' },

    // Backend
    { value: 'Node.js', label: 'Node.js' },
    { value: 'Express.js', label: 'Express.js' },
    { value: 'Django', label: 'Django' },
    { value: 'Flask', label: 'Flask' },
    { value: 'FastAPI', label: 'FastAPI' },
    { value: 'Spring Boot', label: 'Spring Boot' },
    { value: 'ASP.NET Core', label: 'ASP.NET Core' },
    { value: 'Laravel', label: 'Laravel' },
    { value: 'Ruby on Rails', label: 'Ruby on Rails' },
    { value: 'NestJS', label: 'NestJS' },
    { value: 'GraphQL', label: 'GraphQL' },

    // Databases
    { value: 'PostgreSQL', label: 'PostgreSQL' },
    { value: 'MySQL', label: 'MySQL' },
    { value: 'MongoDB', label: 'MongoDB' },
    { value: 'Redis', label: 'Redis' },
    { value: 'Elasticsearch', label: 'Elasticsearch' },
    { value: 'Firebase', label: 'Firebase' },
    { value: 'Supabase', label: 'Supabase' },
    { value: 'Cassandra', label: 'Cassandra' },
    { value: 'DynamoDB', label: 'DynamoDB' },
    { value: 'MariaDB', label: 'MariaDB' },

    // Mobile
    { value: 'React Native', label: 'React Native' },
    { value: 'Flutter', label: 'Flutter' },
    { value: 'iOS', label: 'iOS' },
    { value: 'Android', label: 'Android' },
    { value: 'Ionic', label: 'Ionic' },

    // DevOps & Cloud
    { value: 'Docker', label: 'Docker' },
    { value: 'Kubernetes', label: 'Kubernetes' },
    { value: 'AWS', label: 'AWS' },
    { value: 'Azure', label: 'Azure' },
    { value: 'Google Cloud', label: 'Google Cloud' },
    { value: 'Terraform', label: 'Terraform' },
    { value: 'Ansible', label: 'Ansible' },
    { value: 'Jenkins', label: 'Jenkins' },
    { value: 'GitHub Actions', label: 'GitHub Actions' },
    { value: 'GitLab CI', label: 'GitLab CI' },
    { value: 'Nginx', label: 'Nginx' },

    // Data Science & AI
    { value: 'PyTorch', label: 'PyTorch' },
    { value: 'TensorFlow', label: 'TensorFlow' },
    { value: 'Scikit-learn', label: 'Scikit-learn' },
    { value: 'Pandas', label: 'Pandas' },
    { value: 'NumPy', label: 'NumPy' },
    { value: 'Keras', label: 'Keras' },
    { value: 'LangChain', label: 'LangChain' },
    { value: 'OpenAI API', label: 'OpenAI API' },
    { value: 'Hugging Face', label: 'Hugging Face' },

    // Tools & Others
    { value: 'Git', label: 'Git' },
    { value: 'Jira', label: 'Jira' },
    { value: 'Docker Compose', label: 'Docker Compose' },
    { value: 'Linux', label: 'Linux' },
    { value: 'Bash', label: 'Bash' },
    { value: 'Postman', label: 'Postman' },
    { value: 'Figma', label: 'Figma' },
    { value: 'Adobe XD', label: 'Adobe XD' },
    { value: 'Unit Testing', label: 'Unit Testing' },
    { value: 'TDD', label: 'TDD' },
    { value: 'Agile', label: 'Agile' },
    { value: 'Scrum', label: 'Scrum' },
]
