# Generated by Django 5.2.6 on 2026-04-28 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=10)),
                ('device', models.CharField(blank=True, help_text='Browser / device info', max_length=255)),
                ('location', models.CharField(blank=True, help_text='City / country / IP-based location', max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Time of login/logout event')),
                ('logout_time', models.DateTimeField(blank=True, help_text='If this row represents a logout or session end', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('recruiter', 'Recruiter'), ('employee', 'Employee')], default='employee', help_text='RBAC role for application access', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.FileField(blank=True, help_text='Profile picture or avatar', null=True, upload_to='avatars/')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, default='en', help_text='Preferred language code, e.g. en, fr, de', max_length=20)),
                ('timezone', models.CharField(blank=True, default='UTC', help_text='IANA timezone name, e.g. Europe/Berlin, Asia/Karachi', max_length=64)),
                ('password_last_changed', models.DateTimeField(blank=True, help_text='When the password was last changed', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
